In [1]:
import numpy as np

In [2]:
#making numpy arrays from a list
my_lst = [1,2,3,4,5]
np.array(my_lst)

array([1, 2, 3, 4, 5])

In [3]:
lst = [[1,2,3],[4,5,6]]
np.array(lst)

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
#making arrays using in-built numpy methods
np.arange(0,12,3)

array([0, 3, 6, 9])

In [5]:
#array of all zeroes
np.zeros(4)

array([0., 0., 0., 0.])

In [6]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
#array of all ones
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
#identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
#makes an array with 5 evenly distributed nos including 0 and 12
#not to be confused with arange
np.linspace(0,12,5)

array([ 0.,  3.,  6.,  9., 12.])

In [13]:
#rand chooses random nos from a uniform distribution between 0 and 1
print(np.random.rand(4))
print(np.random.rand(2,2))

[0.14490559 0.6668701  0.53612597 0.75680245]
[[0.24281934 0.75125443]
 [0.08485565 0.69938675]]


In [14]:
#randn chooses random nos from normal distribution over 0
np.random.randn(5)

array([-1.48260171, -0.76503927,  1.26020337,  0.94327122,  1.19349116])

In [16]:
np.random.randn(5,3)

array([[ 0.28217909,  1.38632874,  0.7466257 ],
       [-2.21276649,  1.09817333, -0.10103502],
       [-0.59593162, -0.15086358,  0.1562554 ],
       [ 1.57335028, -0.12573095, -1.82248558],
       [-1.91050537,  0.54237129,  1.02041803]])

In [17]:
#randint chooses random nos between low to high provided.
np.random.randint(1,75,7)

array([45, 66, 68, 33, 11, 38,  7])

In [24]:
#useful attributes and methods of arrays
arr = np.arange(0,5)
mat = np.random.randint(1,15,(2,3))

array([[14,  7,  5],
       [10,  4,  3]])

In [26]:
#reshape - change shape of array
#does not make change to original array, returns new array
mat.reshape(6)

array([[14,  7,  5],
       [10,  4,  3]])

In [29]:
#returns max element in array
arr.max()

4

In [30]:
#returns min element in array
mat.min()

3

In [31]:
#returns index of max element in array
arr.argmax()

4

In [32]:
#returns index of min element in array
#for matrix it counts elements row-wise and returns index accordingly
mat.argmin()

5

In [33]:
#returns shape of array
mat.shape

(2, 3)

In [35]:
#returns type of elements in array
arr.dtype

dtype('int64')